# Generated by Django 5.2.4 on 2026-05-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicknotes', '0003_alter_note_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.TextField(default='Untagged'),
        ),
    ]
